### ISSUE TITLE
data processing pipeline for Entree / p30 book

### ISSUE THREAD

**Issue by sanderlenselink** [tuxdna/BuildingScalaRecommendationEngine#1]
some weeks ago I bought your book Building a Recommendation Engine with Scala. And I’m reading it cq working out your examples.  

I experience a problem on page 30 . . . I  only get the text “Next batch. . . “ and not the following text / counts like “foodlife was recently visited 86 times” etc etc. The program is running for hours but maybe that’s normal because of the big dataset. 
I succeeded to have Kafka and Zookeeper up and running. 
If I check mongo it reports that the dbs “entree exists but is (empty)

My question . . . what could be wrong? 
FYI . . . I’m not a software engineer / programmer but have good practical experiences with this kind of stuff.
I use a slight different directory structure but I suppose that doen’t matter. E.g. the example on page 18 works fine.

Please find attached a screenshot and some output. 
[EntreeDatasetPipeline_output.txt](https://github.com/tuxdna/BuildingScalaRecommendationEngine/files/339274/EntreeDatasetPipeline_output.txt)
![sp5jcv 0](https://cloud.githubusercontent.com/assets/12017033/16452371/5ca827be-3e08-11e6-8bae-778bc10a7d42.PNG)

**Comment by tuxdna** [comment]
@sanderlenselink I think the entree data is not setup properly. I see an error in your output:

```
=== MessageProducer starting up: path=akka://system/user/$a/messageProducer ===
[ERROR] [06/28/2016 18:11:50.380] [system-akka.actor.default-dispatcher-6] [akka://system/user/$a] /home/lvw/programs/saleem/p30_pipeline/data/features.txt (No such file or directory)
java.io.FileNotFoundException: /home/lvw/programs/saleem/p30_pipeline/data/features.txt (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at scala.io.Source$.fromFile(Source.scala:90)
```

Do you have `/home/lvw/programs/saleem/p30_pipeline/data/features.txt` present on your system?

**Comment by sanderlenselink** [comment]
I solved by myself this by reading the error message . . .  grrrrrrr..... 
The system resported that there were no data filtes in /data. By copying the dataset to the /entree directory the problem was solved.

ATTENTION
regarding the example at page 18 you have to copy the .scala and dataset in one directory. And therefore I moved the /data directory to /entree. However, in case of example page30 the data has to be in a separated directory

**Comment by tuxdna** [comment]
@sanderlenselink I am glad it worked for you now. I know the examples could be difficult to work because of different valriables such as 
- different SBT version
- different Scala version
- different libraries could interfere with each other

That's how Scala ecosystem can be sometimes.
